In [1]:
import pandas as pd 
import numpy as np
path1 = "C:/Users/jacob.carey/Desktop/Projects/ConsentRateProjects/user_level_consentv1/data_prep/misc/eu_notices.csv"
path2 = "C:/Users/jacob.carey/Desktop/Projects/ConsentRateProjects/user_level_consentv1/data_prep/mass_athena/mass_athena_original.csv"

In [2]:
athena = pd.read_csv(path2, usecols=
                     ['companyid', 'noticeid', 'host', 'companycountryid',
                      'consentgiven', 'usercountry', 'actiontypeid', 'consenttypeid',
                      'accesstypeid', 'os', 'browser', 'usercorrelationkey'], 
                     dtype={
                         'companyid': np.int8, 
                         'companycountryid': np.int8,
                         'consentgiven': np.int8, 
                         'actiontypeid': np.int8, 
                         'consenttypeid': np.int8,
                         'accesstypeid': np.int8
                     })

In [3]:
athena['noticeid'].unique()

array([  118, 10858, 15446,   547, 16335, 17575, 15534, 15539, 15536,
       17562, 15815, 14497,  3426,  7710, 12550, 15540, 15213, 15541,
       14496, 15542, 17573,   399,  3419, 16340, 15210, 14327,  3273,
       16041, 15533, 14040, 15950, 16336,  8620, 15558, 14689,  6570,
       13230, 17134, 14728, 15556,  8877, 15577, 14093, 16066, 14355,
       14353,  3424, 14817, 18223, 14477, 15569, 15995, 12794, 15570,
       10756, 16356,  6284,  6833, 14571, 15137, 14590, 17385, 18998,
       14629, 14662, 16245, 17563, 15557, 14587,  1006, 17084, 17722,
       15148, 12779, 14681, 14609, 15988,  8835, 14732, 16039, 16133,
       15204, 14898, 14227, 14324, 15245], dtype=int64)

In [4]:
ba = pd.read_csv(path1, usecols=['ClearLanguage', 'CompanyName', 'Industry', 'OnBrand', 'snid'], dtype={
    'ClearLanguage': np.int8,
    'Industry': np.int8,
    'OnBrand': np.int8
})

In [5]:
ba['snid'].unique()

array([  547,   399, 15533, 15534, 15536, 15539, 15540, 15541, 15542,
       15547, 15549, 15551, 15553, 15555, 15556, 15557, 15558, 15559,
       15574, 15576, 15577, 15578, 15579, 15580, 15582, 15586, 15589,
       16335, 16336, 16337, 16338, 16340, 16341, 17421, 12779, 13197,
       13292, 14324, 14401, 14402, 14403, 14404, 14433, 14434, 14436,
       14439, 14448, 14449, 14711, 14712, 14734, 14768, 14817, 14826,
       16324, 16356, 17569, 17579, 17580, 17583, 17584, 17585,  8620,
       15137, 15826, 16078, 14457, 16116, 16125, 16421, 16434, 16436,
       16453, 17459, 18690, 11478, 13067, 13834, 15224, 15672, 15673,
       17453, 19161,  6572, 14662, 14663, 14696, 14866, 14884, 14911,
       15398, 15402, 15642, 15824, 15825, 15843, 15983, 16060, 16061,
       16062, 16130, 16131, 16142, 16176, 16405, 16627, 17232, 17236,
       17348, 17397, 17399, 17491, 17892, 18312, 18314, 18318, 18618,
       18625, 18627, 18636, 18639, 18643, 18686, 18694, 18882,   118,
         134,   143,

In [6]:
merged = athena.merge(ba, right_on='snid', left_on='noticeid')

In [7]:
merged['snid'].unique()

array([  118, 10858, 15446,   547, 16335, 17575, 15534, 15539, 15536,
       17562, 15815, 14497,  3426,  7710, 12550, 15540, 15213, 15541,
       14496, 15542, 17573,   399,  3419, 16340, 15210, 14327,  3273,
       16041, 15533, 14040, 15950, 16336,  8620, 15558, 14689,  6570,
       13230, 17134, 14728, 15556,  8877, 15577, 14093, 16066, 14355,
       14353,  3424, 14817, 18223, 14477, 15569, 15995, 12794, 15570,
       10756, 16356,  6284,  6833, 14571, 15137, 14590, 17385, 18998,
       14629, 14662, 16245, 17563, 15557, 14587,  1006, 17084, 17722,
       15148, 12779, 14681, 14609, 15988,  8835, 14732, 16039, 16133,
       15204, 14898, 14227, 14324, 15245], dtype=int64)

In [8]:
len(merged)

95886230

In [11]:
merged.columns

Index(['companyid', 'noticeid', 'host', 'companycountryid', 'consentgiven',
       'usercountry', 'actiontypeid', 'consenttypeid', 'accesstypeid', 'os',
       'browser', 'usercorrelationkey', 'ClearLanguage', 'CompanyName',
       'Industry', 'OnBrand', 'snid'],
      dtype='object')

In [9]:
del ba

In [10]:
del athena

In [13]:
master = merged.rename(index=str, columns={
    'ClearLanguage': 'clearlanguage',
    'OnBrand': 'onbrand',
    'Industry': 'industry'
})

In [14]:
master.to_csv("C:/Users/jacob.carey/Desktop/Projects/ConsentRateProjects/user_level_consentv1/data_prep/mass_athena/mass_athena_ba_merged_v2.csv")